[build]
  # No build process needed - this is a static site
  publish = "."
  
[build.environment]
  # No environment variables needed for this static app

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache service worker
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache main files
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache CSS
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for SPA behavior (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Fallback redirect for 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
